---
lon-lab-arlf01:
    hostname: 192.168.104.92
    groups:
      - LEAF

lon-lab-arlf02:
  hostname: 192.168.104.93
  groups:
    - LEAF

lon-lab-arlf03:
  hostname: 192.168.104.94
  groups:
    - LEAF

lon-lab-arlf04:
  hostname: 192.168.104.95
  groups:
    - LEAF
    
lon-lab-arsp01:
  hostname: 192.168.104.90
  groups:
    - SPINE

lon-lab-arsp02:
  hostname: 192.168.104.91
  groups:
    - SPINE
