---
all:
  hosts:
    ukfab:
      # Hostname/IP address of APIC
      ansible_host: 192.168.1.1
  
  vars:
      aci_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          # ansible-vault encrypted APIC username
      aci_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          # ansible-vault encrpted APIC password
