---
- name: Get LLDP Neighbors
  hosts: sites_container_lab
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Gather LLDP neighbor information
      arista.eos.eos_facts:
        gather_subset:
          - interfaces

    - name: debug
      debug: 
        var: ansible_net_neighbors