---
all:
  children:
    arista_switches:
      hosts:
        lon-lab-arlf01:
          ansible_host: 192.168.104.92
        lon-lab-arlf02:
          ansible_host: 192.168.104.93
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: arista.eos.eos
        ansible_user: ansible
        ansible_password: ansible
